import { DialogModel } from "../models/debate.model";

const dialogs: DialogModel[] = [
    {
        id: 1,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Le 7 décembre 2048 restera gravé dans les mémoires...",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 2,
    },
    {
        id: 2,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Non pas car l’ail phone 42XS MAX à été annoncé par la firme connu de tous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 3,
    },
    {
        id: 3,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Mais car ce jour là fut le début d'une nouvelle ère pour le climat de notre planète...",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 4,
    },
    {
        id: 4,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Mme. Greenfield, j’ai été mis au courant que cette affaire était votre troisième.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 5,
    },
    {
        id: 5,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Êtes-vous sûre d’être prête pour ce débat ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 6,
    },
    {
        id: 6,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Oui, monsieur le juge.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 7,
    },{
        id: 7,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Monsieur Shades, la défense est-elle prête ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 8,
    },
    {
        id: 8,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Toujours, monsieur le juge.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 9,
    },
    {
        id: 9,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Bien ! Je déclare donc le débat ouvert !",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 10,
    },
    {
        id: 10,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Mme. Greenfield. Vous avez demandé cette audience à cause des modifications climatiques que subit le monde depuis ces dernières années.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 11, 
    },
    {
        id: 11,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Hors, rien n’a jamais prouvé que l’homme a un impact direct sur l’origine de ces anomalies.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 12,
    },
    {
        id: 12,
        speaker: { /* SpriteModel pour Luna */ },
        text: "... (Je ne sais pas quoi répondre à cela…)",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 13,
    },
    {
        id: 13,
        speaker: { /* SpriteModel pour Tomette */ },
        text: "Luna, je sais que c’est ton troisième débat dans ce travail, alors laisse-moi t’aider quelques instants !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 14,
    },
    {
        id: 14,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Tu as une liste de points ici te permettant de répondre au mensonge, aux allégations, ou d’améliorer son point de vue pour qu’il tende de ton côté. Réfléchis bien avant de répondre.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 15,
    }, // TODO
    {
        id: 15,
        speaker: { /* SpriteModel pour Luna (pensant) */ },
        text: "(Effectivement, Tomette a raison. Je dois choisir mes mots avec soin.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 16,
    },
    {
        id: 16,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Mon but est de convaincre, pas de simplement contrer ses arguments. Concentrons-nous sur les faits.)",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 17,
    },
    {
        id: 18,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Monsieur Shade, je comprends vos préoccupations, mais de nombreuses études scientifiques convergent vers une conclusion alarmante.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 19,
    },
    {
        id: 19,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Les émissions de gaz à effet de serre provenant des activités humaines ont augmenté de manière significative, contribuant ainsi au changement climatique.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 20,
    },
    {
        id: 20,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Nous avons la responsabilité de prendre des mesures pour atténuer ces effets néfastes.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 21,
    },
    {
        id: 21,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Les scientifiques ont souvent des opinions divergentes.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 22,
    },
    {
        id: 23,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Certains affirment que le changement climatique est principalement dû à des causes naturelles.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 24,
    },
    {
        id: 24,
        speaker: { /* SpriteModel pour Luna (pensant) */ },
        text: "(Dois-je contrer ses arguments ou souligner la prédominance des preuves en faveur de l'activité humaine?)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 25,
    },
    {
        id: 25,
        speaker: { /* SpriteModel pour Tomette */ },
        text: "Luna, tu peux mentionner le consensus scientifique qui penche en faveur de l'influence humaine.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 26,
    },
    {
        id: 26,
        speaker: { /* SpriteModel pour Tomette */ },
        text: "Cela renforce ton argument de manière crédible.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 27,
    },
    {
        id: 27,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Monsieur Shade, bien que certains scientifiques puissent avoir des opinions divergentes,",
        forceAnswer: false
        canBeAnswered: true,
        answers: [],
        continue: 28,
    },
    {
        id: 28,
        speaker: { /* SpriteModel pour Luna */ },
        text: "la grande majorité s'accorde sur le rôle significatif des activités humaines dans le changement climatique. Un consensus scientifique émerge de multiples études, et nous ne pouvons pas ignorer ces avertissements.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 29,
    },
    {
        id: 29,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Un consensus scientifique émerge de multiples études, et nous ne pouvons pas ignorer ces avertissements.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 30,
    },
    {
        id: 30,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Peut-être, mais ces mêmes scientifiques ont-ils des solutions pratiques pour préserver notre économie",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 31,
    },
    {
        id: 31,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "tout en luttant contre le changement climatique?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 32,
    },
    {
        id: 32,
        speaker: { /* SpriteModel pour Luna (pensant) */ },
        text: "(Il a un point. Dois-je présenter des solutions ou souligner que des innovations sont possibles?)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 33,
    },
    {
        id: 33,
        speaker: { /* SpriteModel pour Tomette */ },
        text: "Luna, enfin ! Mets en avant les innovations et les solutions qui existent. Cela montrera que tu es ouverte aux alternatives.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 34,
    },
    {
        id: 34,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Monsieur Shade, il est vrai que des solutions innovantes émergent, telles que les énergies renouvelables et les pratiques durables.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 35,
    },
    {
        id: 35,
        speaker: { /* SpriteModel pour Luna */ },
        text: "En investissant dans ces technologies, nous pouvons non seulement préserver notre économie mais aussi construire un avenir plus durable pour tous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 36,
    },
    {
        id: 36,
        speaker: { /* SpriteModel pour Juge */ },
        text: "Vos arguments sont notés. Mme. Fourdansldos, je vous prierai de ne plus orienter le porte-paroles de votre camp, n’y même celui du camp adverse, ou des sanctions seront appliquées.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 37,
    },
    {
        id: 37,
        speaker: { /* SpriteModel pour Juge */ },
        text: "N’oubliez pas que le tribunal est un lieu d’ordre et de vérité où l’accusation et la défense doivent pouvoir dialoguer à égalité. Ceci étant dit, veuillez maintenant continuer ce débat, Mr. Shade.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 38,
    },
    {
        id: 38,
        speaker: { /* SpriteModel pour Dorian */ },
        text: "Je vous remercie, votre Honneur. Vous déclarez que les énergies renouvelables et des pratiques durables permettraient de maintenir un avenir plus durable pour nous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 39,
    },
    {
        id: 39,
        speaker: { /* SpriteModel pour Dorian */ },
        text: " Cependant, ce n’est pas le fait d’installer des panneaux solaires coûteux qui va me permettre de gagner et de me nourrir à la fin du mois. Durable pour qui, alors ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40,
    },
    {
        id: 40,
        speaker: { /* SpriteModel pour Luna (pensant) */ },
        text: "(C’est ce sur quoi j’ai travaillé hier avec Tomette… Si je me rappelle bien…)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 41,
    },
    {
        id: 41,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Mr. Shade, vous avez raison, cela ne vous fera pas gagner directement de l’argent,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 42,
    },
    {
        id: 42,
        speaker: { /* SpriteModel pour Luna */ },
        text: "et tout le monde n’est pas capable d’investir dans de telles installations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 43,
    },
    {
        id: 42,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Cependant, chacun devrait participer à son échelle pour pouvoir faire avancer les choses, d’un simple évier arrêté à des installations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 43,
    },
    {
        id: 42,
        speaker: { /* SpriteModel pour Luna */ },
        text: "Malheureusement, il convient plutôt de modifier les politiques et les mœurs afin d’inclure le climat dans nos considérations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 43,
    },
];

export default dialogs;