import { DialogModel } from "../models/debate.model";
const assetRoot = "debate/assets/"
const dialogs: DialogModel[] = [
    {
        id: 0,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Le 7 décembre 2048 restera gravé dans les mémoires...",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 2,
    },
    {
        id: 2,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Non pas car l’ail phone 42XS MAX à été annoncé par la firme connu de tous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 3,
    },
    {
        id: 3,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Mais car ce jour là fut le début d'une nouvelle ère pour le climat de notre planète...",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 4,
    },
    {
        id: 4,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Mme. Greenfield, j’ai été mis au courant que cette affaire était votre troisième.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 5,
    },
    {
        id: 5,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Êtes-vous sûre d’être prête pour ce débat ? (flèche haut, bas pour choisir et flèche droite pour valider)",
        forceAnswer: true,
        canBeAnswered: true,
        answers: [
            {
                text: "Oui, monsieur le juge.",
                continue: 6,
                weight: 1,
            },
            {
                text: "Non, monsieur le juge.",
                continue: 5001,
                weight: 0,
            }
        ],
        continue: 5,
    },
    {
        id: 5001,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Non monsieur le juge.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 5002,
    },
    {
        id: 5002,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Vous n'avez pas vraiment le choix",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [
        ],
        continue: 5,
    },
    {
        id: 6,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Oui, monsieur le juge.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 7,
    },
    {
        id: 7,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Monsieur Shades, la défense est-elle prête ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 8,
    },
    {
        id: 8,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Toujours, monsieur le juge.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 9,
    },
    {
        id: 9,
        speaker: {
            path : "def0",
            name: "Mr. le juge",
            facing: "left",
        },
        text: "Bien ! Je déclare donc le débat ouvert !",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 10,
    },
    {
        id: 10,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Mme. Greenfield. Vous avez demandé cette audience à cause des modifications climatiques que subit le monde depuis ces dernières années.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 11, 
    },
    {
        id: 11,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Hors, rien n’a jamais prouvé que l’homme a un impact direct sur l’origine de ces anomalies.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 12,
    },
    {
        id: 12,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "... (Je ne sais pas quoi répondre à cela…)",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 13,
    },
    {
        id: 13,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Luna, je sais que c’est ton troisième débat dans ce travail, alors laisse-moi t’aider quelques instants !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 14,
    },
    {
        id: 14,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Tu as une liste de points ici te permettant de répondre au mensonge, aux allégations, ou d’améliorer son point de vue pour qu’il tende de ton côté. Réfléchis bien avant de répondre.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 15,
    },
    {
        id: 15,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "(Effectivement, Tomette a raison. Je dois choisir mes mots avec soin.",
        forceAnswer: true,
        canBeAnswered: true,
        answers: [
            {
                text: "Parler des études scientifiques.",
                continue: 16,
                weight: 1,
            },
            {
                text: "Parler de l’augmentation de GES des activités humaines.",
                continue: 16,
                weight: 1,
            },
            {
                text: "Parler des besoins humains.",
                continue: 15001,
                weight: 0,
            },
        ],
        continue: 15,
    },
    {
        id: 15001,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Monsieur Shade, il s’agit d’un besoin humain pour l’homme de libérer le climat du réchauffement climatique !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 15002,
    },
    {
        id: 15002,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "right",
        },
        text: "Quand bien même auriez-vous raison, je ne vois pas très bien en quoi cela répond à ma question !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 21,
    },
    {
        id: 16,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Mon but est de convaincre, pas de simplement contrer ses arguments. Concentrons-nous sur les faits.)",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 18,
    },
    {
        id: 18,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Monsieur Shade, je comprends vos préoccupations, mais de nombreuses études scientifiques convergent vers une conclusion alarmante.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 19,
    },
    {
        id: 19,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Les émissions de gaz à effet de serre provenant des activités humaines ont augmenté de manière significative, contribuant ainsi au changement climatique.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 20,
    },
    {
        id: 20,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Nous avons la responsabilité de prendre des mesures pour atténuer ces effets néfastes.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 21,
    },
    {
        id: 21,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Les scientifiques ont souvent des opinions divergentes.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 23,
    },
    {
        id: 23,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Certains affirment que le changement climatique est principalement dû à des causes naturelles.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 24,
    },
    {
        id: 24,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "(Dois-je contrer ses arguments ou souligner la prédominance des preuves en faveur de l'activité humaine?)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 25,
    },
    {
        id: 25,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Luna, tu peux mentionner le consensus scientifique qui penche en faveur de l'influence humaine.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 26,
    },
    {
        id: 26,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Cela renforce ton argument de manière crédible.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 27,
    },
    {
        id: 27,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Monsieur Shade, bien que certains scientifiques puissent avoir des opinions divergentes,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 28,
    },
    {
        id: 28,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "la grande majorité s'accorde sur le rôle significatif des activités humaines dans le changement climatique.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 29,
    },
    {
        id: 29,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Un consensus scientifique émerge de multiples études, et nous ne pouvons pas ignorer ces avertissements.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 30,
    },
    {
        id: 30,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Peut-être, mais ces mêmes scientifiques ont-ils des solutions pratiques pour préserver notre économie",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 31,
    },
    {
        id: 31,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "tout en luttant contre le changement climatique?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 32,
    },
    {
        id: 32,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "(Il a un point. Dois-je présenter des solutions ou souligner que des innovations sont possibles?)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 33,
    },
    {
        id: 33,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Luna, enfin ! Mets en avant les innovations et les solutions qui existent. Cela montrera que tu es ouverte aux alternatives.",
        forceAnswer: true,
        canBeAnswered: true,
        answers: [
            {
                "text": "Suivre les conseils de Tomette.",
                continue: 33001,
                weight: 1,
            },
            {
                "text": "S’engager dans le soutien de la fission nucléaire",
                continue: 34,
                weight: 1,
            }
        ],
        continue: 33,
    },
    {
        id: 33001,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Monsieur Shade, il est vrai que des solutions innovantes émergent, telles que l’énergie de fission nucléaire et -",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 33002,
    },
    {
        id: 33002,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Je ne suis pas sûr que la fission nucléaire soit une solution “innovante”, Mme Greenfield…",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 36,
    },
    {
        id: 34,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Monsieur Shade, il est vrai que des solutions innovantes émergent, telles que les énergies renouvelables et les pratiques durables.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 35,
    },
    {
        id: 35,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "En investissant dans ces technologies, nous pouvons non seulement préserver notre économie mais aussi construire un avenir plus durable pour tous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 36,
    },
    {
        id: 36,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Vos arguments sont notés. Mme. Fourdansldos, je vous prierai de ne plus orienter le porte-paroles de votre camp, n’y même celui du camp adverse, ou des sanctions seront appliquées.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 37,
    },
    {
        id: 37,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "N’oubliez pas que le tribunal est un lieu d’ordre et de vérité où l’accusation et la défense doivent pouvoir dialoguer à égalité. Ceci étant dit, veuillez maintenant continuer ce débat, Mr. Shade.",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 38,
    },
    {
        id: 38,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Je vous remercie, votre Honneur. Vous déclarez que les énergies renouvelables et des pratiques durables permettraient de maintenir un avenir plus durable pour nous.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 39,
    },
    {
        id: 39,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Cependant, ce n’est pas le fait d’installer des panneaux solaires coûteux qui va me permettre de gagner et de me nourrir à la fin du mois. Durable pour qui, alors ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40,
    },
    {
        id: 40,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "(C’est ce sur quoi j’ai travaillé hier avec Tomette… Si je me rappelle bien…)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [
            {
                text: "Parler de l’investissement dans les énergies renouvelables.",
                continue: 41,
                weight: 1,
            },
            {
                text: "Parler de la participation de chacun.",
                continue: 41,
                weight: 1,
            },
            {
                text: "Parler des moeurs et politiques qui doivent inclure le climat.",
                continue: 41,
                weight: 1,
            },
            {
                text: "Parler des batteries rechargeables.",
                continue: 40001,
                weight: 1,
            },
            
        ],
        continue: 40,
    },
    {
        id: 40001,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Mr. Shade, vous avez raison, cela ne vous fera pas gagner directement de l’argent,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40002,
    },
    {
        id: 40002,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "et tout le monde n’a pas forcément accès à ces installations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40003,
    },
    {
        id: 40003,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Cependant, des solutions telles que des batteries rechargeables permettent le stockage et le transfert de l’énergie.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40004,
    },
    {
        id: 40004,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "right",
        },
        text: "Mme. Greenfield, êtes-vous au courant que les batteries utilisent des matériaux rares,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40005,
    },
    {
        id: 40005,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "right",
        },
        text: "et que l’énergie n’est pas vraiment stockée dans le cas de piles ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 40006,
    },
    {
        id: 40006,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "right",
        },
        text: "De plus, ces installations se fatiguent rapidement...",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 441,
    },
    {
        id: 41,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Mr. Shade, vous avez raison, cela ne vous fera pas gagner directement de l’argent,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 42,
    },
    {
        id: 42,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "et tout le monde n’est pas capable d’investir dans de telles installations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 43,
    },
    {
        id: 43,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Cependant, chacun devrait participer à son échelle pour pouvoir faire avancer les choses, d’un simple évier arrêté à des installations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 44,
    },
    {
        id: 44,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Malheureusement, il convient plutôt de modifier les politiques et les mœurs afin d’inclure le climat dans nos considérations.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 441,
    },
    {
        id: 441,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Mais, Mme. Greenfield, selon les récents évènements, de plus en plus d’espèces s’adaptent aux “nouveaux” environnements :",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 45,
    },
    {
        id: 45,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Il n’y a donc aucun besoin pour l’humain de s’adapter, étant donné que nous sommes déjà entièrement capable de créer des outils.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 46,
    },
    {
        id: 46,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Nous sommes même capables de la fusion atomique, depuis quelques années !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 47,
    },
    {
        id: 47,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Bien que ces espèces s’adaptent aux nouveaux environnements, cela ne veut pas dire que toutes les espèces en sont capables ; bien loin de là.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 48,
    },
    {
        id: 48,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "(Il me semblait avoir des papiers sur ça… ah, là !)",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 49,
    },
    {
        id: 49,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Regardez ce document : Il fait état de blanchissement des récifs coralliens à proximité de nos côtes depuis maintenant au moins 40 ans.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 50,
    },
    {
        id: 50,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Or, ces mêmes coraux permettent à des espèces de se nourrir, voire même de vivre, en se cachant dedans !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 51,
    },
    {
        id: 51,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "L’adaptation est justement la clé ; et dans le cas de l’humain, c’est l’innovation.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 52,
    },
    {
        id: 52,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Enfin, ceci fait partie du cycle naturel !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 53,
    },
    {
        id: 53,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Après tout, les environnements de la Terre ont changé tout au long de son histoire,",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 54,
    },
    {
        id: 54,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "avec des espèces qui disparaissent, et d’autres qui apparaissent.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 55,
    },
    {
        id: 55,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "C’est un cycle naturel, et vous nous dîtes que les activités humaines en seraient la cause ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 56,
    },
    {
        id: 56,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "N’est-ce pas hors de propos ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 57,
    },
    {
        id: 57,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Non, Mr. Shade. Bien au contraire, et nous revenons même au début de notre débat. Vous vous répétez !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 58,
    },
    {
        id: 58,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Votre tête me dit que vous vous rappelez de ce que nous avions parlé : les scientifiques pensent en grande majorité que l’origine est humaine.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 59,
    },
    {
        id: 59,
        speaker: {
            path : "acc1",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Quant au cycle naturel, est-ce donc naturel d’avoir une forte hausse d’incendies, de tsunamis, et même de toxicité, notamment sur les récifs ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 60,
    },
    {
        id: 60,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Il est de toute façon trop tard pour l’humain d’inverser ce cycle; après tout, la machine est déjà en marche.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 61,
    },
    {
        id: 61,
        speaker: {
            path : "def1",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "Si c’est juste un problème de particules, alors dîtes-moi pourquoi l’humain ne pourrait pas juste fabriquer une machine permettant d’inverser cette tendance.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 62,
    },
    {
        id: 62,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Tout simplement car ce n’est pas possible à une échelle mondiale; malgré les tentatives de l’entreprise Carboneo depuis de nombreuses années.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 63,
    },
    {
        id: 63,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Après, il est compliqué de capter l’entièreté du CO2 produit. Mais il n’est jamais trop tard pour inverser le cycle; seulement, ce ne sera ni notre génération, ni la prochaine qui en bénéficierait, mais encore d’autres.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 0,
    },
    { // BONNE REPONSE
        id: 64,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Tomette (Chuchote): *Bien joué, Luna ! Le juge a l’air satisfait !*",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 65,
    },
    {
        id: 65,
        speaker: {
            path : "tomm",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Nous arrivons à la fin de ce débat, il me semble. N’est-ce pas, Mr. Shade ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 66,
    },
    {
        id: 66,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "O-oui, votre Honneur. Je le pense aussi.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 67,
    },
    {
        id: 67,
        speaker: {
            path : "def0",
            name: "Mr. le juge",
            facing: "left",
        },
        text: "Mme Greenfield, je dois dire, vous vous êtes améliorée depuis vos deux premiers débats. Il semblerait que ce soit vous qui tenez raison, cette fois-ci.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 68,
    },
    {
        id: 68,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Je vous remercie, votre Honneur ! Mais cela n’aurait pas été possible sans les conseils de ma chère Tomette.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 69,
    },
    {
        id: 69,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "Hé hé!",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 0,
    },
    { // Mauvaise fin
        id: 70,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Mais enfin, Mr. Shade, vous…",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 71,
    },
    {
        id: 71,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "*raclement de gorge* Mme. Greenfield, il me semble que nous arrivons aux termes de ce débat. N’est-ce pas ?",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 72,
    },
    {
        id: 72,
        speaker: {
            path : "acc0",
            name: "Luna Greenfield",
            facing: "right",
        },
        text: "Votre Honneur, je… !",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 73,
    },
    {
        id: 73,
        speaker: {
            path : "acc0",
            name: "Mr. le juge",
            facing: "right",
        },
        text: "Mme. Greenfield, malgré mon respect envers vous, vous n’avez pas performé correctement aujourd’hui contre Mr. Shade. Je dois avouer que je suis assez déçu, vos deux premiers débats étaient bien plus intéressants.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 74,
    },
    {
        id: 74,
        speaker: {
            path : "def0",
            name: "Dorian Shade",
            facing: "left",
        },
        text: "L’accusation ne semblait pas bien prête, cette fois-ci.",
        forceAnswer: false,
        canBeAnswered: true,
        answers: [],
        continue: 75,
    },
    {
        id: 75,
        speaker: {
            path : "tomm",
            name: "Tomette Fourdansldos",
            facing: "right",
        },
        text: "La prochaine fois, on l’aura, ne t’inquiètes pas !",
        forceAnswer: false,
        canBeAnswered: false,
        answers: [],
        continue: 0,
    },
];

export default dialogs;